config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :option_value_variations
  resources :variations
  resources :option_values
  resources :options
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/variation.rb
class Variation < ApplicationRecord
  belongs_to :product
  has_many :option_value_variations
  has_many :option_values, through: :option_value_variations

  accepts_nested_attributes_for :option_value_variations

  validates :sku, presence: true, uniqueness: true
  validates :quantity, presence: true, numericality: true
  validates :price, presence: true, numericality: true
end

app/controllers/variations_controller.rb
class VariationsController < ApplicationController
  before_action :set_variation, only: [:show, :edit, :update, :destroy]

  # GET /variations
  # GET /variations.json
  def index
    @variations = Variation.all
  end

  # GET /variations/1
  # GET /variations/1.json
  def show
  end

  # GET /variations/new
  def new
    @variation = Variation.new
  end

  # GET /variations/1/edit
  def edit
  end

  # POST /variations
  # POST /variations.json
  def create
    @variation = Variation.new(variation_params)

    respond_to do |format|
      if @variation.save
        format.html { redirect_to @variation, notice: 'Variation was successfully created.' }
        format.json { render :show, status: :created, location: @variation }
      else
        format.html { render :new }
        format.json { render json: @variation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variations/1
  # PATCH/PUT /variations/1.json
  def update
    respond_to do |format|
      if @variation.update(variation_params)
        format.html { redirect_to @variation, notice: 'Variation was successfully updated.' }
        format.json { render :show, status: :ok, location: @variation }
      else
        format.html { render :edit }
        format.json { render json: @variation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variations/1
  # DELETE /variations/1.json
  def destroy
    @variation.destroy
    respond_to do |format|
      format.html { redirect_to variations_url, notice: 'Variation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variation
      @variation = Variation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def variation_params
      params.require(:variation).permit(:product_id, :quantity, :price, :sku)
    end
end

app/helpers/variations_helper.rb
module VariationsHelper
end

app/views/variations/_form.html.erb
<%= form_with(model: variation, local: true) do |form| %>
  <% if variation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(variation.errors.count, "error") %> prohibited this variation from being saved:</h2>

      <ul>
      <% variation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :sku %>
    <%= form.text_field :sku %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/variations/edit.html.erb
<h1>Editing Variation</h1>

<%= render 'form', variation: @variation %>

<%= link_to 'Show', @variation %> |
<%= link_to 'Back', variations_path %>

app/views/variations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Variations</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Sku</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variations.each do |variation| %>
      <tr>
        <td><%= variation.product %></td>
        <td><%= variation.quantity %></td>
        <td><%= variation.price %></td>
        <td><%= variation.sku %></td>
        <td><%= link_to 'Show', variation %></td>
        <td><%= link_to 'Edit', edit_variation_path(variation) %></td>
        <td><%= link_to 'Destroy', variation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variation', new_variation_path %>

app/views/variations/new.html.erb
<h1>New Variation</h1>

<%= render 'form', variation: @variation %>

<%= link_to 'Back', variations_path %>

app/views/variations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @variation.product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @variation.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @variation.price %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @variation.sku %>
</p>

<%= link_to 'Edit', edit_variation_path(@variation) %> |
<%= link_to 'Back', variations_path %>